import type { NextPage } from "next";
import Head from "next/head";
import CategoryList from "../components/categoryList/categoryList";

import { Typography } from "@mui/material";
import Script from "next/script";
import { useEffect, useState } from "react";
import Button from "../components/button";
import CategoryListType from "../components/categoryListType";
import Slice from "../components/slice";
import { Category, CategoryData, MovieType, TvShowType, Type } from "../models";
import getCategoryDetail from "./api/categoryApi";
import styles from "./home.module.scss";
import { useRouter } from "next/router";
const Home: NextPage = () => {
    const [sliceData, setSliceData] = useState<CategoryData[]>();
    const [category, setCategory] = useState<string>(Category.movie);
    const [type, setType] = useState<Type>(MovieType.upcoming);
    const router = useRouter();
    // const [genres, setGenres] = useState<Genres>();

    // Get 10 feature movies to set slice
    useEffect(() => {
        try {
            const params = { page: 1 };
            const getList = async () => {
                const response = await getCategoryDetail.getCategory(category, type, {
                    params,
                });
                setSliceData(response.results.slice(0, 3));
            };

            getList();
        } catch (error) {
            console.log("Error Fetch Slice API");
        }
    }, [category, type]);

    const handleRedirectClick = (cate: string) => {
        router.push(`/${cate}`);
    };

    return (
        <div>
            <Head>
                <title>Movies App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
                    rel="stylesheet"
                    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
                    crossOrigin="anonymous"
                />
            </Head>
            <Script
                src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
                crossOrigin="anonymous"
            ></Script>
            <main>
                <div className={styles.container}>
                    {sliceData && <Slice data={sliceData} cate={category} />}
                    <div className={`${styles.wrapper}`}>
                        <div className={`container py-5 mb-5 ${styles.tvShow}`}>
                            <Typography className="fs-5 pt-5 text-uppercase text-secondary">
                                Online Steaming
                            </Typography>
                            <Typography className="display-4 pb-3">Watch Shows Online</Typography>
                            <CategoryList cate={Category.tv} type={TvShowType.top_rated} />
                        </div>

                        <div className="container-fluid py-5 bg-dark text-center">
                            <Typography className="fs-5 pt-5 text-uppercase text-secondary">
                                FIND ANYWHERE ELSE
                            </Typography>
                            <Typography className="display-4 pb-3 text-white">
                                Movies For You
                            </Typography>
                            <CategoryListType
                                cate={Category.movie}
                                type={MovieType.popular}
                                textColor="white"
                            />
                            <Button
                                text="Browse All Movies"
                                onClick={() => {
                                    handleRedirectClick(Category.movie);
                                }}
                            />
                        </div>
                        <div className="container-fluid py-5 text-center">
                            <Typography className="fs-5 pt-5 text-uppercase text-secondary">
                                FIND ANYWHERE ELSE
                            </Typography>
                            <Typography className="display-4 pb-3 ">Tv Shows For You</Typography>
                            <CategoryListType
                                cate={Category.tv}
                                type={TvShowType.on_the_air}
                                textColor="black"
                            />
                            <Button
                                text="Browse All Tv Shows"
                                onClick={() => {
                                    handleRedirectClick(Category.tv);
                                }}
                            />
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
};

export default Home;
