import type { NextPage } from "next";
import Head from "next/head";
import CategoryList from "../components/categoryList/categoryList";

import { useEffect, useState } from "react";
import Slice from "../components/slice";
import { Category, CategoryData, MovieType, TvShowType, Type } from "../models";
import getCategoryDetail from "./api/categoryApi";
import styles from "./home.module.scss";
import Script from "next/script";
const Home: NextPage = () => {
    const [sliceData, setSliceData] = useState<CategoryData[]>();
    const [category, setCategory] = useState<string>(Category.movie);
    const [type, setType] = useState<Type>(MovieType.upcoming);

    // Get 10 feature movies to set slice
    useEffect(() => {
        try {
            const params = { page: 1 };
            const getList = async () => {
                const response = await getCategoryDetail.getCategory(category, type, {
                    params,
                });
                setSliceData(response.results.slice(0, 10));
            };
            getList();
        } catch (error) {
            console.log("Error Fetch Slice API");
        }
    }, [category, type]);

    return (
        <div>
            <Head>
                <title>Movies App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
                    rel="stylesheet"
                    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
                    crossOrigin="anonymous"
                />
            </Head>
            <Script
                src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
                crossOrigin="anonymous"
            ></Script>
            <main>
                <div className={styles.container}>
                    {sliceData && <Slice data={sliceData} cate={category} />}
                    <CategoryList
                        title="Trending Now"
                        cate={Category.movie}
                        type={MovieType.popular}
                    />
                    <CategoryList
                        title="Tv Show Trending"
                        cate={Category.tv}
                        type={TvShowType.popular}
                    />
                    <CategoryList
                        title="Top Rated Movies"
                        cate={Category.movie}
                        type={MovieType.top_rated}
                    />
                    <CategoryList
                        title="Top Rated Tv Shows"
                        cate={Category.tv}
                        type={TvShowType.top_rated}
                    />
                    <CategoryList
                        title="Featured Movies"
                        cate={Category.movie}
                        type={MovieType.upcoming}
                    />
                    <CategoryList
                        title="On The Air"
                        cate={Category.tv}
                        type={TvShowType.on_the_air}
                    />
                </div>
            </main>
        </div>
    );
};

export default Home;
