import type { NextPage } from "next";
import Head from "next/head";
import CategoryList from "../components/categoryList/categoryList";

import { useEffect, useState } from "react";
import Slice from "../components/slice";
import { Category, CategoryData, MovieType, TvShowType, Type } from "../models";
import getCategoryDetail from "./api/categoryApi";
import styles from "./home.module.scss";
const Home: NextPage = () => {
    const [sliceData, setSliceData] = useState<CategoryData[]>();
    const [category, setCategory] = useState<string>(Category.movie);
    const [type, setType] = useState<Type>(MovieType.upcoming);

    // Get 10 feature movies to set slice
    useEffect(() => {
        try {
            const params = { page: 1 };
            const getList = async () => {
                const response = await getCategoryDetail.getCategory(category, type, {
                    params,
                });
                setSliceData(response.results.slice(0, 10));
            };
            getList();
        } catch (error) {
            console.log("Error Fetch Slice API");
        }
    }, [category, type]);

    return (
        <div>
            <Head>
                <title>Movies App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className={styles.container}>
                    {sliceData && <Slice data={sliceData} cate={category} />}
                    <CategoryList
                        title="Trending Now"
                        cate={Category.movie}
                        type={MovieType.popular}
                    />
                    <CategoryList
                        title="Tv Show Trending"
                        cate={Category.tv}
                        type={TvShowType.popular}
                    />
                    <CategoryList
                        title="Top Rated Movies"
                        cate={Category.movie}
                        type={MovieType.top_rated}
                    />
                    <CategoryList
                        title="Top Rated Tv Shows"
                        cate={Category.tv}
                        type={TvShowType.top_rated}
                    />
                    <CategoryList
                        title="Featured Movies"
                        cate={Category.movie}
                        type={MovieType.upcoming}
                    />
                    <CategoryList
                        title="On The Air"
                        cate={Category.tv}
                        type={TvShowType.on_the_air}
                    />
                </div>
            </main>
        </div>
    );
};

export default Home;
